usbcommander.socket.port=${SOCKET_PORT}
jwt.secret=${JWT_SECRET}
jwt.refresh-token-expiration-seconds=${REFRESH_TOKEN_LIFE}
jwt.access-token-expiration-seconds=${ACCESS_TOKEN_LIFE}
usbcommander.logger.route=${LOG_ROUTE}